spring.application.name=magicWebsite
server.port=8080

# R2DBC
spring.r2dbc.url=r2dbc:postgresql://postgres:5432/marketplace_db
spring.r2dbc.username=crsnam
spring.r2dbc.password=postgres

# Flyway
spring.flyway.enabled=true
spring.flyway.url=jdbc:postgresql://postgres:5432/marketplace_db
spring.flyway.user=crsnam
spring.flyway.password=postgres
spring.flyway.schemas=cards_schema
spring.flyway.default-schema=cards_schema

spring.r2dbc.properties.schema=cards_schema

# Security
spring.security.oauth2.resourceserver.jwt.issuer-uri=http://keycloak:8080/realms/cards
